spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_disk?useSSL=true&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 20210505
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 80

#开启驼峰命名  解决带下划线字段查询为null
# 数据库字段user_name 对应实体userName 不开启查询为null
mybatis:
  configuration:
     map-underscore-to-camel-case: true



